version: 2

# --------------------------------
# common : base
# --------------------------------

base_node: &base_node
  docker:
    - image: circleci/node:8.10.0-browsers

# --------------------------------
# common : steps
# --------------------------------

step_run_node_env_info: &step_run_node_env_info
  name: 'Print Environment Info'
  command: |
    . ./.circleci/utils.sh
    print_heading "environment versions:"
    print_os_versions
    print_node_versions
    print_docker_versions

step_run_update_npm: &step_run_update_npm
  name: 'Update NPM To The most recent release'
  shell: /bin/bash
  command: sudo npm install -g npm@next

step_run_init: &step_run_init
  name: 'Initialize'
  shell: /bin/bash
  command: npm run init

step_lint: &step_lint
  name: 'Lint'
  command: npm run lint

step_npm_audit: &step_npm_audit
  name: 'Audit NPM Dependencies'
  command: npm run npm:audit

step_test: &step_test
  name: 'Tests'
  command: npm run test

# --------------------------------
# jobs
# --------------------------------

jobs:
  push-job:
    <<: *base_node
    steps:
      - checkout
      - run: *step_run_update_npm
      - run: *step_run_node_env_info
      - run: *step_run_init
      - run: *step_npm_audit
      - run: *step_lint
      - run: *step_test

# --------------------------------
# workflows
# --------------------------------

workflows:
  version: 2
  build:
    jobs:
      - push-job
