env:
  browser: true
  es6: true
  mocha: true
  jest: true
globals:
  __DEV__: true
overrides:
  - files:
    - "**/*.test.js"
    - "**/*.test.jsx"
    env:
      jest: true
extends:
  - 'airbnb'
  - 'eslint-config-prettier'
  - 'prettier'
  - 'prettier/react'
parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  import/prefer-default-export:
    - off
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - avoid-escape
  semi:
    - error
    - never
  comma-dangle:
    - error
    - always-multiline
  react/jsx-filename-extension:
    - 1
    - extensions:
      - js
      - jsx
  no-underscore-dangle:
    - off
  operator-linebreak:
    - off
  no-nested-ternary:
    - off
  no-console:
    - off
  object-curly-newline:
    - off
  no-shadow:
    - off
  arrow-parens:
    - error
    - as-needed
    - requireForBlockBody: true
  arrow-body-style:
    - error
    - as-needed
